[theme]
# primary accent color for interactive elements
primaryColor = "#27374D"

# background color for the main content area
backgroundColor = "#DDE6ED"

# background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#9DB2BF"

# color used for almost all text
textColor = "#27374D"

# font family for all text in the app, except code blocks.
font = "sans serif"
